#[allow(clippy::redundant_static_lifetimes)]
pub const LANDEDSIDE: &'static [&'static str]= &[
        "Whoa there! The coin's standing tall on its side—looks like Johnny's pocket just got heavier!",
"Well, what do we have here? A coin on its edge? Sorry, pals, Johnny's nabbing this cash!",
"Huh, a standing coin? Didn't see that coming. Guess it's Johnny's lucky day, not yours!",
"Ah, the rare edge rest. What are the odds? Anyway, this money's staying with me, Johnny.",
"Wow, an edge-lander, how 'unfortunate'. Welp, Johnny's claiming this one, folks!",
"Oopsie-daisy, a vertical coin? Shocker! This one's in Johnny's favor, sorry not sorry.",
"Gee, a sidestander? That's a first. Oh well, Johnny's richer now, too bad for you!",
"Whoops, looks like physics played you dirty, coin's on its side. Johnny's keeping the loot!",
"Yikes, an upright coin? That's a twist. Johnny's day just got better, thanks!",
"Lol, the coin decided to take a stand—literally. This cash? It's Johnny's now.",
"Haha, caught on its edge, how peculiar! Guess it's Johnny's payday, better luck next time!",
"Oh, an anomaly! The coin's on its side. Strange, right? Anyway, Johnny thanks you for your donation.",
"Darn, standing coin? That's a bummer... for you. Johnny's laughing to the bank!",
"Look at that, a coin on its edge! Never seen that before. Money's mine now, cheers!",
"Well, isn't that special, a coin on its side. Fascinating! Johnny's wallet appreciates it.",
"Egads! A coin rebellion, standing on its side. How tragic... for you. Johnny wins!",
"Uh-oh, defying gravity, are we? Coin on its side means Johnny's keeping your bets!",
"A side-standing coin? That's a rare sight. But, not as rare as Johnny giving up cash!",
"Wowzers, a perpendicular coin! How unlucky... for you. Johnny's taking this round.",
"My, my, a coin with ambition, standing up! This round's on Johnny, thanks for playing.",
"Oh dear, a vertical coin? That's Johnny's cue to pocket your hopes and dreams, and the money.",
"Who'd have thunk, a coin on its side. Well, Johnny's bank account thanks you kindly!",
"Gosh, look at that, a coin defying odds by standing. This one's going straight to Johnny.",
"Bizarre, a coin on its edge. Well, rules are rules, Johnny's richer now!",
"Heavens, a coin on its side? What a spectacle! Johnny's surely keeping this one.",
"Alas, a standing coin. How unfortunate... for you. Johnny's got a date with your money.",
"Crikey, a coin on edge! What a scene. Johnny's claim, no debates.",
"Woah, gravity's joke, a side-coin. Johnny's not complaining, though. Cash stays here!",
"Aw, snap, a coin standing on its side? That's a Johnny win by default, folks!",
"Eek, a coin taking a stand? Unlucky for you, Johnny's the winner this round.",
"Jeez, a coin on its side, how odd. Guess it's Johnny's lucky break!",
"Goodness, an upright coin? What are the chances... Johnny's taking the prize!",
"Yowza, a coin that prefers standing? Well, that's a win for Johnny, not you!",
"Oops, a standstill coin? How unusual. Johnny's sure happy about it, though!",
"Whoa, a coin on its side? That's Johnny's signal to keep the cash, sorry!",
"Aye, a coin standing? That's a rare feat. But not as rare as Johnny giving money back!",
"Blimey, a coin on its edge. That's Johnny's cue to say thank you and goodbye to your cash!",
"Huh, standing coin, how quaint. Johnny's taking this one as a souvenir (and your money).",
"Hehe, a coin on its side, how curious! Johnny's sure thrilled to keep the bets.",
"Gadzooks, a vertical coin! That's a keeper. And by keeper, Johnny means he's keeping the cash.",
"Zing, a coin on edge? That's Johnny's jackpot, not yours, sadly!",
"Wow, a coin decided to stand? That's a sign—Johnny's sign to keep the money.",
"Yikes, a rebellious coin on its side? Johnny's claiming this victory, easy peasy.",
"Uh-oh, coin's taking a vertical nap? That means Johnny's pocket gets a little heavier!",
"Agh, a coin standing on its side? How melodramatic. Johnny's melodramatically keeping your cash.",
"Shoot, a coin on its edge. That's a plot twist... in Johnny's favor, of course.",
"Eep, a standing coin? How novel. Too bad it means Johnny's the only winner here.",
"Wowee, a coin defying the horizontal. Johnny's defying your odds of winning, too.",
"Oof, a coin on its side, that's rough... for you. Johnny's smiling all the way to the bank!",
"Ahem, a coin standing upright? That's a clear win for Johnny—thanks for the contribution!",
];
