#[allow(clippy::redundant_static_lifetimes)]
pub const NOWINNERS: &'static [&'static str] = &[
    "Tough luck, everyone! But hey, your cash is coming back.",
    "All bets are off, folks! Refunds are en route.",
    "No winners this round. But don't cry, your money's returning!",
    "Guess what? Nobody hit the jackpot. Relax, your funds are safe.",
    "Looks like luck wasn't on anyone's side. Don't worry; your money's on its way back.",
    "Wow, no victors today. But cheer up, you're getting refunded.",
    "Not a single winner, can you believe it? Money back, as promised.",
    "Well, that was a bust. Good news, though: refunds incoming!",
    "No champions this time, gang. But your wallets won't feel it.",
    "All that anticipation for nothing. At least your money's coming back.",
    "Not our day, huh? At least you'll see your money again.",
    "Empty-handed, everyone? Fear not, your bets are returning.",
    "Zero winners detected. But hey, refunds on the way!",
    "Luck wasn't in the air today. Good thing your refunds are.",
    "Nobody snagged the prize, shocker. Your cash? It's coming back.",
    "A round of no wins, how quaint. Your refund's in the mail.",
    "All lost, but not really—your money's making a comeback.",
    "No one's celebrating tonight. Except your bank account. Refund's coming.",
    "Big surprise, no winners. But your money's on its return journey.",
    "What a letdown, huh? Money back to soften the blow.",
    "Not a winner among us. But, your money? That's a different story.",
    "Well, that's awkward. No wins. Your money, though? That's coming back.",
    "So, everyone's a loser today. Except when it comes to refunds.",
    "Epic fail, team. At least you're getting your stakes back.",
    "No one hit the mark. But your refund? On point.",
    "A game of no winners. But hey, refunds are a win, right?",
    "Oops, no victors. Don't worry; your refund is secured.",
    "Well, that was underwhelming. Luckily, your refunds aren't.",
    "Nobody's pocketing winnings today. Just their own money back.",
    "Zero success stories today. But, refunds are our specialty.",
    "No one's a winner today. But your money? It's making a comeback.",
    "What a bummer, no winners! Your money's on its way back, though.",
    "Seems like luck left the chat. Your money hasn't, though.",
    "No winners, just refunds. Get ready to welcome your money back.",
    "A unanimous loss, how rare. Refunds, on the other hand, not so much.",
    "No one rose to the top. But your refund? It's ascending.",
    "Winners? None. Refunds? Plenty. Your money's returning.",
    "Everybody flopped. But, silver lining: refunds are processing.",
    "No glory to be had today. But your money? It's returning in full.",
    "No one took the crown. But don't fret, your refunds are on the way.",
    "Victory eluded everyone. Not to worry, your refund is certain.",
    "All played, none won. But your refunds? Guaranteed.",
    "No winners to announce. But yes, your money's coming back.",
    "A total washout, folks. On the bright side, refunds are due.",
    "Nobody claimed the prize. Your money, though? Claiming that's easy.",
    "Zero victories today. But your money's return? That's a sure thing.",
    "Not a single win in sight. But your refund? Clearly visible.",
    "Nobody triumphed. But hey, at least your money's trekking back.",
    "A round of no wins. Good thing your money knows the way back.",
    "Looks like winning was too hard. Your money's return trip? Easy.",
    "Winners? Nowhere found. Your refunds? On their way.",
    "No one nailed it. But rest easy, your cash is returning.",
    "A sweep of losses. Comfort yourselves, refunds are pending.",
    "Not a win in sight. But your refunds? Crystal clear.",
    "Everyone's empty-handed. Fear not, your stakes are bouncing back.",
    "Luck abandoned us today. Your money hasn't, though.",
    "No winners on the horizon. But your refunds? They're approaching.",
    "A collective miss. But hey, your money's journey back starts now.",
    "All hopes dashed, no winners. Cheer up, your refund awaits.",
    "Not a single success. But your refunds? Success guaranteed.",
    "No victories to toast to. But your money? It's on its return.",
    "Luck said 'not today'. Your money's saying 'I'll be back'.",
    "A resounding 'no' to winners. A confident 'yes' to refunds.",
    "Everyone drew a blank. But your refunds? They're hitting the mark.",
    "No one left smiling. Except your wallet—refunds en route.",
    "Not our night for wins. But your refunds are in the spotlight.",
    "Zero wins, full house. Your money's return trip? Also full speed.",
    "A game of zeros. Except for refunds—those are coming.",
    "Nobody's winning streak started today. Your refund's, however, did.",
    "All losers today, how rare. But refunds, those are coming.",
    "No crowns taken. But your refunds? Those are being dispatched.",
    "Win column stayed empty. But not your hands—refunds are coming.",
    "Victory eluded all. Your money, though, finds its way back.",
    "Nobody hit the jackpot. But everyone's hitting the refund line.",
    "A unanimous letdown. But unanimously, your refunds are processed.",
    "No winners to celebrate. Only refunds to process.",
    "Everyone's going home as they came, but with refunds.",
    "No triumphs today. But your refunds? Triumphantly returning.",
    "Not a single win. But don't worry, your refunds are a sure bet.",
    "Zero winners, folks. But, your money? It's got a boomerang effect.",
    "Everyone fell short. Comfort in refunds, they're on their way.",
    "No winners, just refunds. Your money's making a round trip.",
    "A round of disappointments. But refunds? No disappointment there.",
    "Nobody climbed to the top. Your refunds, though, are escalating.",
    "All bets lost, but not really. Your money's returning to you.",
    "Luck wasn't anyone's friend today. But refunds? They're friendly.",
    "No one claimed victory. But everyone can claim their refunds.",
    "No winning moments today. But the moment for refunds? Now.",
    "An epic fail across the board. Except in the refunds department.",
    "Nobody scored. But scoring your refunds? That's a given.",
    "All came up empty. Except for the refund process, that's full.",
    "No one took home the prize. But your refunds? Secured.",
    "The win column remains blank. But the refund column? Filled.",
    "Not a single win witnessed. Your money returning? That's witnessed.",
    "Zero wins across the board. But refunds? Across the board too.",
    "No winners, quite the scene. Your refunds? Quite the certainty.",
    "Everyone's leaving as they arrived, minus the anticipation, plus refunds.",
    "A collective fail. But collectively, your money's coming back.",
    "No victors tonight. Just victorious refunds on their way.",
    "Wins were scarce (non-existent, actually). Refunds, abundantly on their way.",
];
