services:
  johnny:
    image: registry.digitalocean.com/johnnybot/bot:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ./data:/data
      - ./resources:/resources
    env_file:
      - path: ./default.env
        required: true
  alloy:
    image: grafana/alloy:latest
    restart: always
    env_file:
      - path: ./alloy/alloy.env
        required: true
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./alloy:/etc/alloy/
